version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: finance-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: finance-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  financedb:
    image: mysql:8.0.23
    container_name: finance-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: finance
      MYSQL_ROOT_PASSWORD: local
      MYSQL_USER: dan
      MYSQL_PASSWORD: qwerty123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdatafinance:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: finance-phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=financedb
      - PMA_USER=root
      - PMA_PASSWORD=local
    depends_on: 
      - financedb
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdatafinance:
    driver: local